"""DivergenceSplitter public API."""

from divergencesplitter.clock import MonotonicTime, TimeProvider
from divergencesplitter.condition import (
    All,
    Any,
    Condition,
    Detected,
    Elapsed,
    FallingEdge,
    Hold,
    Not,
    Nth,
    Once,
    ResetWhen,
    RisingEdge,
    Then,
)
from divergencesplitter.configuration import (
    load_scenario_module,
    validate_scenarios,
    validate_split_count,
)
from divergencesplitter.detector import (
    ColorRangeConfig,
    ColorRangeDetector,
    DifferenceHashSimilarityConfig,
    DifferenceHashSimilarityDetector,
    ImageDetector,
    MeanAbsoluteSimilarityConfig,
    MeanAbsoluteSimilarityDetector,
    MeanBrightnessDetector,
    PhaseCorrelationConfig,
    PhaseCorrelationDetector,
    TemplateMatchConfig,
    TemplateMatchDetector,
    evaluate,
)
from divergencesplitter.detector.models import DetectionResult
from divergencesplitter.frame import (
    CaptureDiagnostics,
    CaptureStateMachine,
    ClipRegion,
    ErrorAction,
    Frame,
    FrameClipError,
    FrameContext,
    FrameNormalizationError,
    FrameNormalizer,
    FrameResizeError,
    FrameSource,
    FrameSourceState,
    ImageArray,
    LatestFrameBuffer,
    OutputSize,
    PublishResult,
    VideoFileDecodeError,
    VideoFileEndOfFileError,
    VideoFileError,
    VideoFileOpenError,
    VideoFileReadBeforeReadyError,
    VideoFileSource,
)
from divergencesplitter.livesplit import (
    LiveSplitConnection,
    LiveSplitSnapshot,
    LiveSplitUpdate,
    LiveSplitUpdateKind,
    TimerPhase,
)
from divergencesplitter.rule import Action, Rule
from divergencesplitter.scenario import Scenario, ScenarioRuntime

__all__ = [
    "Action",
    "All",
    "Any",
    "CaptureDiagnostics",
    "CaptureStateMachine",
    "ClipRegion",
    "ColorRangeConfig",
    "ColorRangeDetector",
    "Condition",
    "Detected",
    "DetectionResult",
    "DifferenceHashSimilarityConfig",
    "DifferenceHashSimilarityDetector",
    "Elapsed",
    "ErrorAction",
    "FallingEdge",
    "Frame",
    "FrameClipError",
    "FrameContext",
    "FrameNormalizationError",
    "FrameNormalizer",
    "FrameResizeError",
    "FrameSource",
    "FrameSourceState",
    "Hold",
    "ImageArray",
    "ImageDetector",
    "LatestFrameBuffer",
    "LiveSplitConnection",
    "LiveSplitSnapshot",
    "LiveSplitUpdate",
    "LiveSplitUpdateKind",
    "MeanAbsoluteSimilarityConfig",
    "MeanAbsoluteSimilarityDetector",
    "MeanBrightnessDetector",
    "MonotonicTime",
    "Not",
    "Nth",
    "Once",
    "OutputSize",
    "PhaseCorrelationConfig",
    "PhaseCorrelationDetector",
    "PublishResult",
    "ResetWhen",
    "RisingEdge",
    "Rule",
    "Scenario",
    "ScenarioRuntime",
    "TemplateMatchConfig",
    "TemplateMatchDetector",
    "Then",
    "TimeProvider",
    "TimerPhase",
    "VideoFileDecodeError",
    "VideoFileEndOfFileError",
    "VideoFileError",
    "VideoFileOpenError",
    "VideoFileReadBeforeReadyError",
    "VideoFileSource",
    "evaluate",
    "load_scenario_module",
    "validate_scenarios",
    "validate_split_count",
]
