"""DivergenceSplitter public API."""

from divergencesplitter.clock import MonotonicTime, TimeProvider
from divergencesplitter.condition import (
    All,
    Any,
    Condition,
    Detected,
    Elapsed,
    FallingEdge,
    Hold,
    Not,
    Nth,
    Once,
    RisingEdge,
    Then,
)
from divergencesplitter.detector import (
    ColorRangeDetector,
    DifferenceHashSimilarityDetector,
    ImageDetector,
    MeanAbsoluteSimilarityDetector,
    MeanBrightnessDetector,
    PhaseCorrelationDetector,
    TemplateMatchDetector,
    evaluate,
)
from divergencesplitter.detector.models import DetectionResult
from divergencesplitter.frame import (
    ClipRegion,
    ErrorAction,
    Frame,
    FrameClipError,
    FrameContext,
    FrameNormalizationError,
    FrameNormalizer,
    FrameResizeError,
    FrameSource,
    FrameSourceState,
    ImageArray,
    OutputSize,
    VideoFileDecodeError,
    VideoFileEndOfFileError,
    VideoFileError,
    VideoFileOpenError,
    VideoFileReadBeforeReadyError,
    VideoFileSource,
)
from divergencesplitter.livesplit import (
    LiveSplitSnapshot,
    LiveSplitUpdate,
    LiveSplitUpdateKind,
    TimerPhase,
)
from divergencesplitter.rule import Action, Rule
from divergencesplitter.scenario import (
    RuleDefinition,
    ScenarioDefinition,
    ScenarioRuntime,
)

__all__ = [
    "Action",
    "All",
    "Any",
    "ClipRegion",
    "ColorRangeDetector",
    "Condition",
    "Detected",
    "DetectionResult",
    "DifferenceHashSimilarityDetector",
    "Elapsed",
    "ErrorAction",
    "FallingEdge",
    "Frame",
    "FrameClipError",
    "FrameContext",
    "FrameNormalizationError",
    "FrameNormalizer",
    "FrameResizeError",
    "FrameSource",
    "FrameSourceState",
    "Hold",
    "ImageArray",
    "ImageDetector",
    "LiveSplitSnapshot",
    "LiveSplitUpdate",
    "LiveSplitUpdateKind",
    "MeanAbsoluteSimilarityDetector",
    "MeanBrightnessDetector",
    "MonotonicTime",
    "Not",
    "Nth",
    "Once",
    "OutputSize",
    "PhaseCorrelationDetector",
    "RisingEdge",
    "Rule",
    "RuleDefinition",
    "ScenarioDefinition",
    "ScenarioRuntime",
    "TemplateMatchDetector",
    "Then",
    "TimeProvider",
    "TimerPhase",
    "VideoFileDecodeError",
    "VideoFileEndOfFileError",
    "VideoFileError",
    "VideoFileOpenError",
    "VideoFileReadBeforeReadyError",
    "VideoFileSource",
    "evaluate",
]
