"""DivergenceSplitter public API."""

from divergencesplitter.clock import MonotonicTime, TimeProvider
from divergencesplitter.condition import (
    All,
    Any,
    Condition,
    Detected,
    Elapsed,
    FallingEdge,
    Hold,
    Not,
    Nth,
    Once,
    ResetWhen,
    RisingEdge,
    Then,
)
from divergencesplitter.detector import (
    ColorRangeConfig,
    ColorRangeDetector,
    DifferenceHashSimilarityConfig,
    DifferenceHashSimilarityDetector,
    ImageDetector,
    MeanAbsoluteSimilarityConfig,
    MeanAbsoluteSimilarityDetector,
    MeanBrightnessDetector,
    PhaseCorrelationConfig,
    PhaseCorrelationDetector,
    TemplateMatchConfig,
    TemplateMatchDetector,
    evaluate,
)
from divergencesplitter.detector.models import DetectionResult
from divergencesplitter.frame import (
    ClipRegion,
    ErrorAction,
    Frame,
    FrameClipError,
    FrameContext,
    FrameNormalizationError,
    FrameNormalizer,
    FrameResizeError,
    FrameSource,
    FrameSourceState,
    ImageArray,
    OpenCvCameraSource,
    OutputSize,
    VideoFileSource,
)
from divergencesplitter.livesplit import LiveSplitConnection
from divergencesplitter.rule import Action, Rule
from divergencesplitter.scenario import Scenario

__all__ = [
    "Action",
    "All",
    "Any",
    "ClipRegion",
    "ColorRangeConfig",
    "ColorRangeDetector",
    "Condition",
    "Detected",
    "DetectionResult",
    "DifferenceHashSimilarityConfig",
    "DifferenceHashSimilarityDetector",
    "Elapsed",
    "ErrorAction",
    "FallingEdge",
    "Frame",
    "FrameClipError",
    "FrameContext",
    "FrameNormalizationError",
    "FrameNormalizer",
    "FrameResizeError",
    "FrameSource",
    "FrameSourceState",
    "Hold",
    "ImageArray",
    "ImageDetector",
    "LiveSplitConnection",
    "MeanAbsoluteSimilarityConfig",
    "MeanAbsoluteSimilarityDetector",
    "MeanBrightnessDetector",
    "MonotonicTime",
    "Not",
    "Nth",
    "Once",
    "OpenCvCameraSource",
    "OutputSize",
    "PhaseCorrelationConfig",
    "PhaseCorrelationDetector",
    "ResetWhen",
    "RisingEdge",
    "Rule",
    "Scenario",
    "TemplateMatchConfig",
    "TemplateMatchDetector",
    "Then",
    "TimeProvider",
    "VideoFileSource",
    "evaluate",
]
