"""Generate the Windows distribution license inventory and license files.

The inventory is computed from the Windows release dependency closure of the
``divergencesplitter-ui`` distribution. The closure walks ``Requires-Dist``
edges of the root distribution, evaluates environment markers for a Windows
target, and resolves each requirement to a distribution installed in the
current environment. It never queries a network and never lists every
installed package.

Python package licenses are collected from distribution metadata and license
files. Runtime components that have no Python distribution metadata are added
separately under ``assets``. Flutter/Dart notices are generated by Flutter
tooling in ``flutter_assets/NOTICES.Z``. The NDI Runtime is an explicit release
root, with its licensing notice and third-party notices separate from its MIT
Python binding.

For each inventoried component the generator writes license texts directly to
the Windows distribution. Installed distribution metadata and files are the
primary source. Only components listed in ``LICENSE_TEXT_FALLBACKS`` may use a
Git-managed license text. The application license comes directly from the
repository ``LICENSE``; CPython and its additional notices come from the Python
runtime staged by Flet.

Generation is deterministic: packages are emitted sorted by their normalized
name, license files are sorted by their normalized sub-path, and every run
over the same environment produces identical JSON. The ``--check`` mode
rebuilds the expected inventory and fails on missing or extra entries and
license or text differences. Package versions always match; runtime asset
versions match only when the expected asset explicitly has one. The license screen
covers third-party components only, so the own DivergenceSplitter
distributions are excluded from the emitted inventory via an explicit,
documented set.
"""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import sys
from collections.abc import Mapping
from importlib import metadata
from pathlib import Path, PurePosixPath
from typing import NamedTuple, NotRequired, TypedDict

from packaging.licenses import (
    InvalidLicenseExpression,
    canonicalize_license_expression,
)
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_ROOT = Path(__file__).resolve().parent
LICENSES_ROOT = TOOLS_ROOT / "licenses"
ROOT_DISTRIBUTION = "divergencesplitter-ui"
SCHEMA_VERSION = 7
APPLICATION_NAME = "DivergenceSplitter"
APPLICATION_LICENSE = "MIT"
APPLICATION_LICENSE_PATH = REPO_ROOT / "LICENSE"
LICENSE_NAME_STARTS = ("license", "licence", "copying", "notice")

# The NDI runtime is conveyed alongside the MIT-licensed ``ndi-python`` binding
# but is licensed separately by Vizrt NDI AB. It is emitted as assets instead
# of being folded into the ``ndi-python`` package so the two are never confused.
NDI_PACKAGE = "ndi-python"
NDI_RUNTIME_ASSET_NAME = "NDI Runtime"
NDI_RUNTIME_NOTICES_ASSET_NAME = "NDI Runtime Third-Party Notices"
NDI_RUNTIME_LICENSE = "Licensing Notice"
NDI_RUNTIME_NOTICES_LICENSE = "Third-party notices"
NDI_RUNTIME_NOTICES_PATH = "NDIlib/Processing.NDI.Lib.Licenses.txt"
NDI_LICENSE_DOCUMENT_PATH = REPO_ROOT / "THIRD_PARTY_LICENSES" / "NDI.md"

# MPL-2.0 requires that the Corresponding Source be made available. Rather than
# building a dependency metadata system, MPL components get a short pointer to
# their upstream source appended to their bundled license text.
MPL_LICENSE_ID = "MPL-2.0"
MPL_SOURCE_NOTE = (
    "=== MPL-2.0 Source Availability ===\n"
    "{name} {version} is distributed under the Mozilla Public License 2.0.\n"
    "The Corresponding Source for this component is available from its\n"
    "upstream project and from the Python Package Index:\n"
    "https://pypi.org/project/{name}/{version}/#files"
)


class LicenseTextFallback(NamedTuple):
    path: Path
    reason: str


LICENSE_TEXT_FALLBACKS: dict[str, LicenseTextFallback] = {
    "flet": LicenseTextFallback(
        LICENSES_ROOT / "Apache-2.0.txt",
        "the installed wheel declares Apache-2.0 but ships no license text",
    ),
    "dart-bridge": LicenseTextFallback(
        LICENSES_ROOT / "dart_bridge-MIT.txt",
        "the native runtime artifact does not contain a license text",
    ),
}

EXCLUDED_DISTRIBUTIONS: dict[str, str] = {
    "divergencesplitter": "own package, not a third-party license",
    "divergencesplitter-runtime": "own package, not a third-party license",
    "divergencesplitter-ui": "own package, not a third-party license",
}


class Override(NamedTuple):
    license: str
    reason: str


class PackageEntry(TypedDict):
    name: str
    version: str
    license: str
    license_file: str


class ApplicationEntry(TypedDict):
    name: str
    license: str
    license_file: str


class AssetEntry(TypedDict):
    name: str
    version: NotRequired[str]
    license: str
    license_file: str


class InventoryDocument(TypedDict):
    schema_version: int
    application: ApplicationEntry
    packages: list[PackageEntry]
    assets: list[AssetEntry]


OVERRIDES: dict[str, Override] = {
    "windows-capture-device-list": Override(
        "MIT",
        "release metadata carries no license fields and the repository LICENSE is MIT",
    ),
    "livesplit-bridge-client": Override(
        "MIT",
        "release metadata License is the full MIT text, not an SPDX expression",
    ),
    "protobuf": Override(
        "BSD-3-Clause",
        "release metadata License is '3-Clause BSD License', not an SPDX expression",
    ),
    "opencv-contrib-python": Override(
        "Apache-2.0",
        "release metadata License is 'Apache 2.0', not an SPDX expression",
    ),
}


def _windows_environment() -> dict[str, str]:
    return {
        "implementation_name": sys.implementation.name,
        "implementation_version": platform.python_version(),
        "os_name": "nt",
        "platform_machine": platform.machine(),
        "platform_python_implementation": platform.python_implementation(),
        "platform_release": platform.release(),
        "platform_system": "Windows",
        "platform_version": sys.version,
        "python_full_version": platform.python_version(),
        "python_version": ".".join(platform.python_version().split(".")[:2]),
        "sys_platform": "win32",
        "extra": "",
    }


def release_closure(
    installed: Mapping[str, metadata.Distribution],
    *,
    additional_roots: tuple[str, ...] = (),
) -> dict[str, metadata.Distribution]:
    """Return the Windows release closure keyed by normalized package name.

    ``installed`` maps normalized package names to the available distribution
    metadata so the closure can be built from fixtures in tests.
    ``additional_roots`` includes optional backends collected by PyInstaller.
    """

    environment = _windows_environment()
    closure: dict[str, metadata.Distribution] = {}
    pending = [ROOT_DISTRIBUTION, *additional_roots]
    while pending:
        requested = pending.pop()
        key = canonicalize_name(requested)
        if key in closure:
            continue
        dist = installed.get(key)
        if dist is None:
            raise RuntimeError(
                f"{requested!r} is in the release closure but is not installed"
            )
        closure[key] = dist
        for requirement_string in dist.requires or ():
            requirement = Requirement(requirement_string)
            if requirement.marker is not None and not requirement.marker.evaluate(
                environment
            ):
                continue
            child = canonicalize_name(requirement.name)
            if child not in closure:
                pending.append(requirement.name)
    return closure


def installed_distributions() -> dict[str, metadata.Distribution]:
    """Index the current environment by normalized package name."""

    return {
        canonicalize_name(dist.metadata["Name"]): dist
        for dist in metadata.distributions()
    }


def _license_from_metadata(dist: metadata.Distribution) -> str | None:
    expression = dist.metadata.get("License-Expression")
    if expression and expression != "UNKNOWN":
        return expression
    license_value = (dist.metadata.get("License") or "").strip()
    if license_value and license_value != "UNKNOWN":
        return license_value
    classifiers = dist.metadata.get_all("Classifier") or ()
    for classifier in classifiers:
        if classifier.startswith("License :: OSI Approved :: "):
            return classifier.removeprefix("License :: OSI Approved :: ")
        if classifier.startswith("License :: "):
            return classifier.removeprefix("License :: ")
    return None


def resolve_license(dist: metadata.Distribution) -> str:
    """Resolve one distribution to a single SPDX license expression."""

    key = canonicalize_name(dist.metadata["Name"])
    override = OVERRIDES.get(key)
    if override is not None:
        return override.license
    value = _license_from_metadata(dist)
    if value is None:
        raise RuntimeError(
            f"cannot resolve a license for {dist.metadata['Name']!r}; "
            "add an explicit override with a documented reason"
        )
    try:
        return canonicalize_license_expression(value)
    except InvalidLicenseExpression:
        raise RuntimeError(
            f"license {value!r} for {dist.metadata['Name']!r} is not an SPDX "
            "expression; add an explicit override with a documented reason"
        ) from None


def _dist_info_subpath(file_path: object) -> str | None:
    """Return a distribution file path relative to its ``.dist-info`` dir."""

    parts = PurePosixPath(str(file_path).replace("\\", "/")).parts
    for index, segment in enumerate(parts):
        if segment.endswith(".dist-info"):
            return "/".join(parts[index + 1 :])
    return None


def _declared_license_files(
    dist: metadata.Distribution,
) -> list[tuple[str, str]]:
    """Read the license files named by ``License-File`` metadata.

    PEP 639 paths may be relative to the ``.dist-info/licenses`` directory or
    to the ``.dist-info`` directory itself, so both are tried. A declared file
    that cannot be read is a metadata inconsistency and fails loudly.
    """

    resolved: list[tuple[str, str]] = []
    for declared_path in dist.metadata.get_all("License-File") or ():
        read_path: str | None = None
        content: str | None = None
        for candidate in (f"licenses/{declared_path}", declared_path):
            text = dist.read_text(candidate)
            if text is not None:
                read_path, content = candidate, text
                break
        if read_path is None or content is None:
            raise RuntimeError(
                f"declared license file {declared_path!r} for "
                f"{dist.metadata['Name']!r} cannot be read"
            )
        resolved.append((read_path, content))
    return resolved


def _scanned_license_files(
    dist: metadata.Distribution,
) -> list[tuple[str, str]]:
    """Discover license files under the distribution's ``.dist-info`` dir.

    This catches components whose metadata omits ``License-File`` while the
    installed wheel still ships license texts, including nested sub-licenses.
    """

    scanned: dict[str, str] = {}
    for file_path in dist.files or ():
        subpath = _dist_info_subpath(file_path)
        if subpath is None:
            continue
        if not PurePosixPath(subpath).name.lower().startswith(LICENSE_NAME_STARTS):
            continue
        text = dist.read_text(subpath)
        if text is not None:
            scanned[subpath] = text
    return sorted(scanned.items())


def _fallback_license_text(component: str) -> str | None:
    """Return a component-specific fallback text, if one is explicitly set."""

    fallback = LICENSE_TEXT_FALLBACKS.get(canonicalize_name(component))
    if fallback is None:
        return None
    if not fallback.path.is_file():
        raise RuntimeError(
            f"license text fallback for {component!r} is missing: {fallback.path}"
        )
    return fallback.path.read_text(encoding="utf-8")


def _contains_mpl(expression: str) -> bool:
    """Return whether an SPDX expression includes MPL-2.0."""

    tokens = expression.replace("(", " ").replace(")", " ").split()
    return MPL_LICENSE_ID in tokens


def _source_availability_note(dist: metadata.Distribution) -> str | None:
    """Return an MPL-2.0 source-availability note when the component needs one.

    The note is best-effort: a component whose license cannot be resolved is
    not treated as MPL, because its own license-text collection already fails
    loudly when it is genuinely broken.
    """

    try:
        expression = resolve_license(dist)
    except RuntimeError:
        return None
    if not _contains_mpl(expression):
        return None
    return MPL_SOURCE_NOTE.format(
        name=dist.metadata["Name"],
        version=dist.metadata["Version"],
    )


def license_text(dist: metadata.Distribution) -> str:
    """Collect every license text shipped by the installed distribution.

    The NDI runtime notices are deliberately not collected here: they license
    the separately distributed NDI Runtime, not the MIT-licensed ``ndi-python``
    binding, and are emitted as their own assets by ``ndi_runtime_assets``.
    """

    entries: dict[str, str] = {}
    for read_path, content in _declared_license_files(dist):
        entries[read_path] = content
    for read_path, content in _scanned_license_files(dist):
        entries[read_path] = content
    if not entries:
        fallback_text = _fallback_license_text(dist.metadata["Name"])
        if fallback_text is None:
            raise RuntimeError(
                f"cannot collect any license text for {dist.metadata['Name']!r}"
            )
        text = fallback_text
    else:
        blocks = [
            f"=== {read_path} ===\n{entries[read_path]}"
            for read_path in sorted(entries)
        ]
        text = "\n\n".join(blocks)
    source_note = _source_availability_note(dist)
    if source_note is not None:
        return f"{text}\n\n{source_note}"
    return text


def _write_text(distribution_root: Path, relative_path: str, text: str) -> None:
    target = resolve_license_file(relative_path, distribution_root)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8", newline="\n")


def resolve_license_file(relative_path: str, distribution_root: Path) -> Path:
    """Resolve a distribution-relative file reference without allowing escape."""
    relative = Path(relative_path)
    if relative.is_absolute() or ".." in relative.parts:
        raise RuntimeError(f"invalid license_file reference: {relative_path!r}")
    root = distribution_root.resolve()
    target = (root / relative).resolve()
    if not target.is_relative_to(root):
        raise RuntimeError(f"invalid license_file reference: {relative_path!r}")
    return target


def application_entry(distribution_root: Path) -> ApplicationEntry:
    """Copy the project LICENSE and return its distribution inventory entry."""
    relative_path = "licenses/application/DivergenceSplitter.txt"
    target = resolve_license_file(relative_path, distribution_root)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(APPLICATION_LICENSE_PATH, target)
    return {
        "name": APPLICATION_NAME,
        "license": APPLICATION_LICENSE,
        "license_file": relative_path,
    }


def ndi_runtime_assets(
    closure: dict[str, metadata.Distribution], distribution_root: Path
) -> list[AssetEntry]:
    """Write NDI's project notice and installed binding notice separately."""
    dist = closure.get(canonicalize_name(NDI_PACKAGE))
    if dist is None:
        return []
    runtime_license = "licenses/runtime/NDI-Runtime.txt"
    third_party_notices = "licenses/runtime/NDI-Runtime-Third-Party-Notices.txt"
    _write_text(
        distribution_root,
        runtime_license,
        NDI_LICENSE_DOCUMENT_PATH.read_text(encoding="utf-8"),
    )
    notice_path = dist.locate_file(NDI_RUNTIME_NOTICES_PATH)
    if not notice_path.is_file():
        raise RuntimeError(f"ndi-python NDI notice is missing: {notice_path}")
    _write_text(
        distribution_root,
        third_party_notices,
        notice_path.read_text(encoding="utf-8"),
    )
    return [
        {
            "name": NDI_RUNTIME_ASSET_NAME,
            "license": NDI_RUNTIME_LICENSE,
            "license_file": runtime_license,
        },
        {
            "name": NDI_RUNTIME_NOTICES_ASSET_NAME,
            "license": NDI_RUNTIME_NOTICES_LICENSE,
            "license_file": third_party_notices,
        },
    ]


def runtime_component_assets(
    staged_python_runtime: Path, distribution_root: Path
) -> list[AssetEntry]:
    """Collect CPython and runtime notices from Flet's staged Python runtime."""
    cpython_source = staged_python_runtime / "LICENSE.txt"
    if not cpython_source.is_file():
        raise RuntimeError(
            f"staged Flet Python runtime has no LICENSE.txt: {cpython_source}"
        )
    cpython_reference = "licenses/CPython.txt"
    cpython_target = resolve_license_file(cpython_reference, distribution_root)
    cpython_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cpython_source, cpython_target)
    assets: list[AssetEntry] = [
        {
            "name": "CPython",
            "license": "Python Software Foundation License",
            "license_file": cpython_reference,
        }
    ]

    dart_fallback = _fallback_license_text("dart_bridge")
    if dart_fallback is None:
        raise RuntimeError("dart_bridge requires an explicit license text fallback")
    dart_reference = "licenses/dart_bridge.txt"
    _write_text(distribution_root, dart_reference, dart_fallback)
    assets.append(
        {"name": "dart_bridge", "license": "MIT", "license_file": dart_reference}
    )

    license_dir = staged_python_runtime / "licenses"
    notice_files = (
        sorted(path for path in license_dir.rglob("*") if path.is_file())
        if license_dir.is_dir()
        else []
    )
    if notice_files:
        blocks = [
            f"=== {path.relative_to(staged_python_runtime).as_posix()} ===\n"
            f"{path.read_text(encoding='utf-8')}"
            for path in notice_files
        ]
        notice_reference = "licenses/runtime/Flet-Python-runtime-notices.txt"
        _write_text(distribution_root, notice_reference, "\n\n".join(blocks))
        assets.append(
            {
                "name": "Flet embedded Python runtime third-party notices",
                "license": "Third-party notices",
                "license_file": notice_reference,
            }
        )
    return assets


def build_inventory(
    closure: dict[str, metadata.Distribution],
    *,
    staged_python_runtime: Path,
    distribution_root: Path,
) -> InventoryDocument:
    """Resolve all release licenses and write their files into the distribution."""
    packages: list[PackageEntry] = []
    for key in sorted(closure):
        if key in EXCLUDED_DISTRIBUTIONS:
            continue
        dist = closure[key]
        reference = f"licenses/packages/{canonicalize_name(dist.metadata['Name'])}.txt"
        _write_text(distribution_root, reference, license_text(dist))
        packages.append(
            {
                "name": dist.metadata["Name"],
                "version": dist.metadata["Version"],
                "license": resolve_license(dist),
                "license_file": reference,
            }
        )
    assets = runtime_component_assets(staged_python_runtime, distribution_root)
    assets.extend(ndi_runtime_assets(closure, distribution_root))
    inventory: InventoryDocument = {
        "schema_version": SCHEMA_VERSION,
        "application": application_entry(distribution_root),
        "packages": packages,
        "assets": assets,
    }
    inventory_path = distribution_root / "license_inventory.json"
    inventory_path.write_text(
        json.dumps(inventory, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    validate_inventory_files(inventory, distribution_root)
    return inventory


def validate_inventory_files(
    inventory: InventoryDocument, distribution_root: Path
) -> None:
    """Require every inventory reference to resolve to a nonempty file."""
    entries = [inventory["application"], *inventory["packages"], *inventory["assets"]]
    for entry in entries:
        path = resolve_license_file(entry["license_file"], distribution_root)
        if not path.is_file() or path.stat().st_size == 0:
            raise RuntimeError(
                f"license file was not generated: {entry['license_file']}"
            )


def render_third_party_notices(
    inventory: InventoryDocument, *, distribution_root: Path
) -> str:
    """Render notices from the exact license files generated for the distribution."""
    groups: dict[str, list[str]] = {}
    for entry in [
        inventory["application"],
        *inventory["packages"],
        *inventory["assets"],
    ]:
        path = resolve_license_file(entry["license_file"], distribution_root)
        if not path.is_file():
            raise RuntimeError(
                f"license file referenced by inventory is missing: {path}"
            )
        text = path.read_text(encoding="utf-8")
        version = entry.get("version")
        label = f"{entry['name']} {version}" if version else entry["name"]
        groups.setdefault(text, []).append(f"{label} — {entry['license']}")
    lines = [
        "DivergenceSplitter Windows Distribution — Third-Party Notices",
        "",
        "License texts below were generated from the resolved release dependencies",
        "and runtime artifacts. Flutter and Dart dependency notices are provided by",
        "DivergenceSplitter/flutter_assets/NOTICES.Z, the authoritative source for",
        "Flutter, Flet Dart packages, serious_python, and other pub dependencies.",
    ]
    for text in sorted(groups):
        names = ", ".join(sorted(groups[text], key=str.casefold))
        lines.extend(["", "=" * 78, names, "=" * 78, "", text.rstrip()])
    return "\n".join(lines).rstrip() + "\n"


def staged_python_runtime(root: Path) -> Path:
    """Find the single Python runtime expanded by the Flet Windows build."""
    build_root = (
        root / "packages" / "divergencesplitter-ui" / "build" / "flutter" / "build"
    )
    candidates = sorted(
        path / "python"
        for path in build_root.glob("build_python_*")
        if (path / "python" / "python.exe").is_file()
        and (path / "python" / "LICENSE.txt").is_file()
    )
    if len(candidates) != 1:
        raise RuntimeError(
            f"Expected exactly one staged Flet Python runtime under {build_root}; "
            f"found {len(candidates)}"
        )
    return candidates[0]


def generate_from_installed_environment(
    *, root: Path, distribution_root: Path
) -> InventoryDocument:
    """Build the Windows dependency closure and generate distribution licenses."""
    closure = release_closure(
        installed_distributions(), additional_roots=(NDI_PACKAGE,)
    )
    return build_inventory(
        closure,
        staged_python_runtime=staged_python_runtime(root),
        distribution_root=distribution_root,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root containing the Flet build",
    )
    parser.add_argument(
        "--distribution-root",
        type=Path,
        default=REPO_ROOT / "dist" / "windows" / "DivergenceSplitter",
        help="directory where inventory and license files are written",
    )
    args = parser.parse_args()
    inventory = generate_from_installed_environment(
        root=args.root, distribution_root=args.distribution_root
    )
    print(
        f"Generated license inventory for {len(inventory['packages'])} Python packages"
    )


if __name__ == "__main__":
    main()
