"""Generate and verify the UI inventory of Python packages and runtime assets.

The inventory is computed from the Windows release dependency closure of the
``divergencesplitter-ui`` distribution. The closure walks ``Requires-Dist``
edges of the root distribution, evaluates environment markers for a Windows
target, and resolves each requirement to a distribution installed in the
current environment. It never queries a network and never lists every
installed package.

Python package licenses are collected from distribution metadata and license
files. Runtime components that have no Python distribution metadata are added
separately under ``assets``. Flutter/Dart notices are generated by Flutter
tooling in ``flutter_assets/NOTICES.Z``. The NDI Runtime is an explicit release
root, with its licensing notice and third-party notices separate from its MIT
Python binding.

For each inventoried component the generator also bundles the full license
text files shipped by the installed distribution, so the license screen can
reproduce the actual license texts (not just SPDX identifiers) that are
redistributed inside the executable. Some releases declare an SPDX expression
in metadata but omit every license file from the wheel (``flet`` is one such
distribution); for those a canonical text vendored under ``tools/licenses`` is
used so the inventory still reproduces the license rather than failing. The
application's own MIT text from the repository ``LICENSE`` is included as the
``application`` section. Components under MPL-2.0 also carry a short note
pointing at where their upstream source can be obtained.

Generation is deterministic: packages are emitted sorted by their normalized
name, license files are sorted by their normalized sub-path, and every run
over the same environment produces identical JSON. The ``--check`` mode
rebuilds the expected inventory and fails on missing or extra entries and
license or text differences. Package versions always match; runtime asset
versions match only when the expected asset explicitly has one. The license screen
covers third-party components only, so the own DivergenceSplitter
distributions are excluded from the emitted inventory via an explicit,
documented set.
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
from collections.abc import Mapping
from importlib import metadata
from pathlib import Path, PurePosixPath
from typing import NamedTuple, NotRequired, TypedDict

from packaging.licenses import (
    InvalidLicenseExpression,
    canonicalize_license_expression,
)
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_ROOT = Path(__file__).resolve().parent
UI_MODULE_ROOT = (
    REPO_ROOT / "packages" / "divergencesplitter-ui" / "src" / "divergencesplitter_ui"
)
INVENTORY_PATH = UI_MODULE_ROOT / "license_inventory.json"
LICENSES_ROOT = TOOLS_ROOT / "licenses"
ROOT_DISTRIBUTION = "divergencesplitter-ui"
SCHEMA_VERSION = 6
APPLICATION_NAME = "DivergenceSplitter"
APPLICATION_LICENSE = "MIT"
APPLICATION_LICENSE_PATH = REPO_ROOT / "LICENSE"
CPYTHON_LICENSE_PATH = TOOLS_ROOT / "licenses" / "CPython.txt"
LICENSE_NAME_STARTS = ("license", "licence", "copying", "notice")

# The NDI runtime is conveyed alongside the MIT-licensed ``ndi-python`` binding
# but is licensed separately by Vizrt NDI AB. It is emitted as assets instead
# of being folded into the ``ndi-python`` package so the two are never confused.
NDI_PACKAGE = "ndi-python"
NDI_RUNTIME_ASSET_NAME = "NDI Runtime"
NDI_RUNTIME_NOTICES_ASSET_NAME = "NDI Runtime Third-Party Notices"
NDI_RUNTIME_LICENSE = "Licensing Notice"
NDI_RUNTIME_NOTICES_LICENSE = "Third-party notices"
NDI_RUNTIME_NOTICES_PATH = "NDIlib/Processing.NDI.Lib.Licenses.txt"
NDI_LICENSE_DOCUMENT_PATH = REPO_ROOT / "THIRD_PARTY_LICENSES" / "NDI.md"

# MPL-2.0 requires that the Corresponding Source be made available. Rather than
# building a dependency metadata system, MPL components get a short pointer to
# their upstream source appended to their bundled license text.
MPL_LICENSE_ID = "MPL-2.0"
MPL_SOURCE_NOTE = (
    "=== MPL-2.0 Source Availability ===\n"
    "{name} {version} is distributed under the Mozilla Public License 2.0.\n"
    "The Corresponding Source for this component is available from its\n"
    "upstream project and from the Python Package Index:\n"
    "https://pypi.org/project/{name}/{version}/#files"
)

# Canonical license texts vendored for distributions that declare an SPDX
# expression but ship no license file in their wheel, keyed by that expression.
# They are read like any bundled text so the emitted inventory stays
# deterministic across platforms.
SPDX_LICENSE_TEXTS: dict[str, Path] = {
    "Apache-2.0": TOOLS_ROOT / "licenses" / "Apache-2.0.txt",
}

EXCLUDED_DISTRIBUTIONS: dict[str, str] = {
    "divergencesplitter": "own package, not a third-party license",
    "divergencesplitter-runtime": "own package, not a third-party license",
    "divergencesplitter-ui": "own package, not a third-party license",
}


class Override(NamedTuple):
    license: str
    reason: str


class PackageEntry(TypedDict):
    name: str
    version: str
    license: str
    license_file: str


class ApplicationEntry(TypedDict):
    name: str
    license: str
    license_file: str


class AssetEntry(TypedDict):
    name: str
    version: NotRequired[str]
    license: str
    license_file: str


class InventoryDocument(TypedDict):
    schema_version: int
    application: ApplicationEntry
    packages: list[PackageEntry]
    assets: list[AssetEntry]


OVERRIDES: dict[str, Override] = {
    "windows-capture-device-list": Override(
        "MIT",
        "release metadata carries no license fields and the repository LICENSE is MIT",
    ),
    "livesplit-bridge-client": Override(
        "MIT",
        "release metadata License is the full MIT text, not an SPDX expression",
    ),
    "protobuf": Override(
        "BSD-3-Clause",
        "release metadata License is '3-Clause BSD License', not an SPDX expression",
    ),
    "opencv-contrib-python": Override(
        "Apache-2.0",
        "release metadata License is 'Apache 2.0', not an SPDX expression",
    ),
}


def _windows_environment() -> dict[str, str]:
    return {
        "implementation_name": sys.implementation.name,
        "implementation_version": platform.python_version(),
        "os_name": "nt",
        "platform_machine": platform.machine(),
        "platform_python_implementation": platform.python_implementation(),
        "platform_release": platform.release(),
        "platform_system": "Windows",
        "platform_version": sys.version,
        "python_full_version": platform.python_version(),
        "python_version": ".".join(platform.python_version().split(".")[:2]),
        "sys_platform": "win32",
        "extra": "",
    }


def release_closure(
    installed: Mapping[str, metadata.Distribution],
    *,
    additional_roots: tuple[str, ...] = (),
) -> dict[str, metadata.Distribution]:
    """Return the Windows release closure keyed by normalized package name.

    ``installed`` maps normalized package names to the available distribution
    metadata so the closure can be built from fixtures in tests.
    ``additional_roots`` includes optional backends collected by PyInstaller.
    """

    environment = _windows_environment()
    closure: dict[str, metadata.Distribution] = {}
    pending = [ROOT_DISTRIBUTION, *additional_roots]
    while pending:
        requested = pending.pop()
        key = canonicalize_name(requested)
        if key in closure:
            continue
        dist = installed.get(key)
        if dist is None:
            raise RuntimeError(
                f"{requested!r} is in the release closure but is not installed"
            )
        closure[key] = dist
        for requirement_string in dist.requires or ():
            requirement = Requirement(requirement_string)
            if requirement.marker is not None and not requirement.marker.evaluate(
                environment
            ):
                continue
            child = canonicalize_name(requirement.name)
            if child not in closure:
                pending.append(requirement.name)
    return closure


def installed_distributions() -> dict[str, metadata.Distribution]:
    """Index the current environment by normalized package name."""

    return {
        canonicalize_name(dist.metadata["Name"]): dist
        for dist in metadata.distributions()
    }


def _license_from_metadata(dist: metadata.Distribution) -> str | None:
    expression = dist.metadata.get("License-Expression")
    if expression and expression != "UNKNOWN":
        return expression
    license_value = (dist.metadata.get("License") or "").strip()
    if license_value and license_value != "UNKNOWN":
        return license_value
    classifiers = dist.metadata.get_all("Classifier") or ()
    for classifier in classifiers:
        if classifier.startswith("License :: OSI Approved :: "):
            return classifier.removeprefix("License :: OSI Approved :: ")
        if classifier.startswith("License :: "):
            return classifier.removeprefix("License :: ")
    return None


def resolve_license(dist: metadata.Distribution) -> str:
    """Resolve one distribution to a single SPDX license expression."""

    key = canonicalize_name(dist.metadata["Name"])
    override = OVERRIDES.get(key)
    if override is not None:
        return override.license
    value = _license_from_metadata(dist)
    if value is None:
        raise RuntimeError(
            f"cannot resolve a license for {dist.metadata['Name']!r}; "
            "add an explicit override with a documented reason"
        )
    try:
        return canonicalize_license_expression(value)
    except InvalidLicenseExpression:
        raise RuntimeError(
            f"license {value!r} for {dist.metadata['Name']!r} is not an SPDX "
            "expression; add an explicit override with a documented reason"
        ) from None


def _dist_info_subpath(file_path: object) -> str | None:
    """Return a distribution file path relative to its ``.dist-info`` dir."""

    parts = PurePosixPath(str(file_path).replace("\\", "/")).parts
    for index, segment in enumerate(parts):
        if segment.endswith(".dist-info"):
            return "/".join(parts[index + 1 :])
    return None


def _declared_license_files(
    dist: metadata.Distribution,
) -> list[tuple[str, str]]:
    """Read the license files named by ``License-File`` metadata.

    PEP 639 paths may be relative to the ``.dist-info/licenses`` directory or
    to the ``.dist-info`` directory itself, so both are tried. A declared file
    that cannot be read is a metadata inconsistency and fails loudly.
    """

    resolved: list[tuple[str, str]] = []
    for declared_path in dist.metadata.get_all("License-File") or ():
        read_path: str | None = None
        content: str | None = None
        for candidate in (f"licenses/{declared_path}", declared_path):
            text = dist.read_text(candidate)
            if text is not None:
                read_path, content = candidate, text
                break
        if read_path is None or content is None:
            raise RuntimeError(
                f"declared license file {declared_path!r} for "
                f"{dist.metadata['Name']!r} cannot be read"
            )
        resolved.append((read_path, content))
    return resolved


def _scanned_license_files(
    dist: metadata.Distribution,
) -> list[tuple[str, str]]:
    """Discover license files under the distribution's ``.dist-info`` dir.

    This catches components whose metadata omits ``License-File`` while the
    installed wheel still ships license texts, including nested sub-licenses.
    """

    scanned: dict[str, str] = {}
    for file_path in dist.files or ():
        subpath = _dist_info_subpath(file_path)
        if subpath is None:
            continue
        if not PurePosixPath(subpath).name.lower().startswith(LICENSE_NAME_STARTS):
            continue
        text = dist.read_text(subpath)
        if text is not None:
            scanned[subpath] = text
    return sorted(scanned.items())


def _vendored_license_text(dist: metadata.Distribution) -> str | None:
    """Return a vendored canonical text for a wheel that ships no license file.

    The text is selected by the distribution's resolved SPDX expression when
    that expression has a canonical file under ``tools/licenses``. Returns
    ``None`` when no vendored text applies, so the caller can fail loudly.
    """

    path = SPDX_LICENSE_TEXTS.get(resolve_license(dist))
    if path is None:
        return None
    relative = path.relative_to(REPO_ROOT).as_posix()
    return f"=== {relative} ===\n{path.read_text(encoding='utf-8')}"


def _contains_mpl(expression: str) -> bool:
    """Return whether an SPDX expression includes MPL-2.0."""

    tokens = expression.replace("(", " ").replace(")", " ").split()
    return MPL_LICENSE_ID in tokens


def _source_availability_note(dist: metadata.Distribution) -> str | None:
    """Return an MPL-2.0 source-availability note when the component needs one.

    The note is best-effort: a component whose license cannot be resolved is
    not treated as MPL, because its own license-text collection already fails
    loudly when it is genuinely broken.
    """

    try:
        expression = resolve_license(dist)
    except RuntimeError:
        return None
    if not _contains_mpl(expression):
        return None
    return MPL_SOURCE_NOTE.format(
        name=dist.metadata["Name"],
        version=dist.metadata["Version"],
    )


def license_text(dist: metadata.Distribution) -> str:
    """Collect every license text shipped by the installed distribution.

    The NDI runtime notices are deliberately not collected here: they license
    the separately distributed NDI Runtime, not the MIT-licensed ``ndi-python``
    binding, and are emitted as their own assets by ``ndi_runtime_assets``.
    """

    entries: dict[str, str] = {}
    for read_path, content in _declared_license_files(dist):
        entries[read_path] = content
    for read_path, content in _scanned_license_files(dist):
        entries[read_path] = content
    if not entries:
        vendored = _vendored_license_text(dist)
        if vendored is None:
            raise RuntimeError(
                f"cannot collect any license text for {dist.metadata['Name']!r}"
            )
        text = vendored
    else:
        blocks = [
            f"=== {read_path} ===\n{entries[read_path]}"
            for read_path in sorted(entries)
        ]
        text = "\n\n".join(blocks)
    source_note = _source_availability_note(dist)
    if source_note is not None:
        return f"{text}\n\n{source_note}"
    return text


def ndi_runtime_assets(
    closure: dict[str, metadata.Distribution],
    license_texts: dict[str, str],
) -> list[AssetEntry]:
    """Return the NDI Runtime assets when the NDI binding is in the closure.

    ``ndi-python`` is MIT, but ships the NDI Runtime licensing notice and
    third-party notices. These assets stay distinct from the MIT binding.
    """

    dist = closure.get(canonicalize_name(NDI_PACKAGE))
    if dist is None:
        return []
    notices = dist.locate_file(NDI_RUNTIME_NOTICES_PATH).read_text(encoding="utf-8")
    licensing_file = "runtime/NDI-Runtime.txt"
    notices_file = "runtime/NDI-Runtime-Third-Party-Notices.txt"
    license_texts[licensing_file] = NDI_LICENSE_DOCUMENT_PATH.read_text(
        encoding="utf-8"
    )
    license_texts[notices_file] = notices
    return [
        {
            "name": NDI_RUNTIME_ASSET_NAME,
            "license": NDI_RUNTIME_LICENSE,
            "license_file": licensing_file,
        },
        {
            "name": NDI_RUNTIME_NOTICES_ASSET_NAME,
            "license": NDI_RUNTIME_NOTICES_LICENSE,
            "license_file": notices_file,
        },
    ]


def application_entry(license_texts: dict[str, str]) -> ApplicationEntry:
    """Return application metadata and record the application's license text."""
    license_file = "application/DivergenceSplitter.txt"
    license_texts[license_file] = APPLICATION_LICENSE_PATH.read_text(encoding="utf-8")
    return {
        "name": APPLICATION_NAME,
        "license": APPLICATION_LICENSE,
        "license_file": license_file,
    }


def build_inventory(
    closure: dict[str, metadata.Distribution],
    *,
    assets: list[AssetEntry] | None = None,
    licenses_root: Path = LICENSES_ROOT,
    write_license_files: bool = True,
    generated_license_files: dict[str, str] | None = None,
) -> InventoryDocument:
    """Emit one inventory entry per non-excluded package.

    The own DivergenceSplitter distributions are excluded because their
    licenses are not part of the third-party license screen. Components that
    are not Python distributions (the NDI Runtime) are emitted as assets.
    """

    license_texts = (
        generated_license_files if generated_license_files is not None else {}
    )
    packages: list[PackageEntry] = []
    for key in sorted(closure):
        if key in EXCLUDED_DISTRIBUTIONS:
            continue
        dist = closure[key]
        license_file = f"packages/{canonicalize_name(dist.metadata['Name'])}.txt"
        license_texts[license_file] = license_text(dist)
        packages.append(
            {
                "name": dist.metadata["Name"],
                "version": dist.metadata["Version"],
                "license": resolve_license(dist),
                "license_file": license_file,
            }
        )
    runtime_assets = (
        runtime_component_assets(license_texts) if assets is None else assets
    )
    inventory: InventoryDocument = {
        "schema_version": SCHEMA_VERSION,
        "application": application_entry(license_texts),
        "packages": packages,
        "assets": runtime_assets + ndi_runtime_assets(closure, license_texts),
    }
    if write_license_files:
        write_license_texts(license_texts, licenses_root)
    return inventory


def runtime_component_assets(license_texts: dict[str, str]) -> list[AssetEntry]:
    """Collect licenses for runtime components without Python package metadata."""
    cpython_file = "CPython.txt"
    dart_bridge_file = "dart_bridge-MIT.txt"
    license_texts[cpython_file] = CPYTHON_LICENSE_PATH.read_text(encoding="utf-8")
    license_texts[dart_bridge_file] = (
        TOOLS_ROOT / "licenses" / "dart_bridge-MIT.txt"
    ).read_text(encoding="utf-8")
    assets: list[AssetEntry] = [
        {
            "name": "CPython",
            "license": "Python Software Foundation License",
            "license_file": cpython_file,
        }
    ]
    assets.append(
        {
            "name": "dart_bridge",
            "version": "1.10.0",
            "license": "MIT",
            "license_file": dart_bridge_file,
        }
    )
    return assets


def write_license_texts(license_texts: Mapping[str, str], licenses_root: Path) -> None:
    """Write collected license texts beneath the authoritative licenses root."""
    for relative_path, text in sorted(license_texts.items()):
        target = resolve_license_file(relative_path, licenses_root)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")


def resolve_license_file(relative_path: str, licenses_root: Path) -> Path:
    """Resolve an inventory reference while preventing paths outside its root."""
    relative = Path(relative_path)
    if relative.is_absolute() or ".." in relative.parts:
        raise RuntimeError(f"invalid license_file reference: {relative_path!r}")
    root = licenses_root.resolve()
    target = (root / relative).resolve()
    if not target.is_relative_to(root):
        raise RuntimeError(f"invalid license_file reference: {relative_path!r}")
    return target


def write_inventory(inventory: InventoryDocument) -> None:
    INVENTORY_PATH.write_text(
        json.dumps(inventory, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def render_third_party_notices(
    inventory: InventoryDocument,
    *,
    flet_runtime_notices: str,
    licenses_root: Path = LICENSES_ROOT,
) -> str:
    """Render a distribution-wide notice file, deduplicating identical texts."""
    groups: dict[str, list[str]] = {}
    texts: dict[str, str] = {}
    for entry in [*inventory["packages"], *inventory["assets"]]:
        key = resolve_license_file(entry["license_file"], licenses_root).read_text(
            encoding="utf-8"
        )
        version = entry.get("version")
        label = f"{entry['name']} {version}" if version else entry["name"]
        groups.setdefault(key, []).append(f"{label} — {entry['license']}")
        texts[key] = key
    lines = [
        "DivergenceSplitter Windows Distribution — Third-Party Notices",
        "",
        "Python package distributions and runtime components are listed below.",
        "Flet embedded Python runtime third-party notices are included separately.",
        "Flutter and Dart package notices are provided by Flutter at",
        "DivergenceSplitter/flutter_assets/NOTICES.Z; that generated notice file",
        "is the authoritative source for Flutter, Flet Dart packages, serious_python,",
        "and other pub dependencies.",
    ]
    for key in sorted(groups):
        names = ", ".join(sorted(groups[key], key=str.casefold))
        lines.extend(["", "=" * 78, names, "=" * 78, "", texts[key].rstrip()])
    lines.extend(
        [
            "",
            "=" * 78,
            "Flet embedded Python runtime third-party notices",
            "=" * 78,
            "",
            flet_runtime_notices.rstrip(),
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def check_inventory(
    inventory: InventoryDocument,
    *,
    license_texts: Mapping[str, str],
    licenses_root: Path = LICENSES_ROOT,
) -> bool:
    if not INVENTORY_PATH.exists():
        print(f"missing bundled inventory: {INVENTORY_PATH}")
        return False
    stored = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    mismatched = stored != inventory
    if mismatched:
        print("license inventory metadata differs from the release closure")
    stored_entries = (
        [
            stored.get("application"),
            *stored.get("packages", []),
            *stored.get("assets", []),
        ]
        if isinstance(stored, dict)
        else []
    )
    for entry in stored_entries:
        if not isinstance(entry, dict):
            print("malformed entry in stored license inventory")
            mismatched = True
            continue
        reference = entry.get("license_file")
        if not isinstance(reference, str) or not reference:
            print("stored inventory entry has no license_file")
            mismatched = True
            continue
        try:
            stored_path = resolve_license_file(reference, licenses_root)
        except RuntimeError as error:
            print(error)
            mismatched = True
            continue
        if not stored_path.is_file():
            print(f"missing license file referenced by inventory: {reference}")
            mismatched = True
    referenced: set[str] = set()
    for entry in [
        inventory["application"],
        *inventory["packages"],
        *inventory["assets"],
    ]:
        relative_path = entry["license_file"]
        referenced.add(relative_path)
        try:
            path = resolve_license_file(relative_path, licenses_root)
        except RuntimeError as error:
            print(error)
            mismatched = True
            continue
        if not path.is_file():
            print(f"missing license file: {relative_path}")
            mismatched = True
            continue
        actual_text = path.read_text(encoding="utf-8")
        expected_text = license_texts.get(relative_path)
        if expected_text is None:
            print(f"no generated license text for reference: {relative_path}")
            mismatched = True
        elif actual_text != expected_text:
            print(f"license file content differs: {relative_path}")
            mismatched = True
    unexpected = set(license_texts) - referenced
    if unexpected:
        print(f"generated license text is unreferenced: {sorted(unexpected)}")
        mismatched = True
    return not mismatched


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the stored inventory with the release closure",
    )
    args = parser.parse_args()

    # The Windows executable also bundles the optional NDI input backend.
    closure = release_closure(
        installed_distributions(), additional_roots=("ndi-python",)
    )
    generated_license_files: dict[str, str] = {}
    inventory = build_inventory(
        closure,
        generated_license_files=generated_license_files,
        write_license_files=not args.check,
    )
    if args.check:
        if not check_inventory(inventory, license_texts=generated_license_files):
            raise SystemExit(1)
        print(
            f"license inventory is up to date ({len(inventory['packages'])} packages)"
        )
        return
    write_inventory(inventory)
    print(
        f"wrote {len(inventory['packages'])} packages to {INVENTORY_PATH.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
